-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 18:47:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PRIVADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRIVADO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRIVADO` (
  `id_privado` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(20) NOT NULL,
  `valor_km` FLOAT NOT NULL,
  PRIMARY KEY (`id_privado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PUBLICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PUBLICO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PUBLICO` (
  `id_publico` INT ZEROFILL NOT NULL,
  `rota_pontos` VARCHAR(100) NOT NULL,
  `acessibilidade_pub` TINYINT NOT NULL,
  `lotacao_pub` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_publico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROTAS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROTAS` (
  `id_rotas` INT ZEROFILL NOT NULL,
  `ponto_ini` VARCHAR(45) NOT NULL,
  `ponto_fim` VARCHAR(45) NOT NULL,
  `acessibilidade` TINYINT NOT NULL,
  `tipo_transporte` VARCHAR(7) NOT NULL,
  `valor` FLOAT NOT NULL,
  `rota_pref` TINYINT NOT NULL,
  `lotacao` INT NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `data_rota` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_privado` INT NOT NULL,
  `id_publico` INT NOT NULL,
  PRIMARY KEY (`id_rotas`),
  INDEX `fk_rotas_1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_rotas_2_idx` (`id_publico` ASC) VISIBLE,
  INDEX `fk_rotas_3_idx` (`id_privado` ASC) VISIBLE,
  CONSTRAINT `fk_rotas_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_2`
    FOREIGN KEY (`id_publico`)
    REFERENCES `mydb`.`PUBLICO` (`id_publico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_3`
    FOREIGN KEY (`id_privado`)
    REFERENCES `mydb`.`PRIVADO` (`id_privado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `id_usuario` INT ZEROFILL NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `senha` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
